# Generated by Django 2.2 on 2019-04-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffing.Company')),
            ],
            options={
                'verbose_name': 'role type',
                'verbose_name_plural': 'role types',
            },
        ),
    ]
