# Generated by Django 2.2 on 2019-04-09 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0004_auto_20190409_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_logs', to='staffing.Company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_logs', to='staffing.Employee')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_logs', to='staffing.Role_Type')),
            ],
        ),
    ]
