# Generated by Django 2.2 on 2019-04-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0005_role_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_log',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
